/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.graph.xiaoha.chart.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 图表类型
 */
public enum ChartType implements org.apache.thrift.TEnum {
  HISTORICAL_DATA(0),
  SPREAD_MONTH(1),
  SPREAD_COMMODITY(2),
  FORWARD_CURVE(3);

  private final int value;

  private ChartType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChartType findByValue(int value) { 
    switch (value) {
      case 0:
        return HISTORICAL_DATA;
      case 1:
        return SPREAD_MONTH;
      case 2:
        return SPREAD_COMMODITY;
      case 3:
        return FORWARD_CURVE;
      default:
        return null;
    }
  }
}
