/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.graph.xiaoha.chart.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum XiaoHaChartErrorCode implements org.apache.thrift.TEnum {
  TAG_NOT_FOUND(2000),
  TAG_EXISTS(2001),
  CHART_NOT_FOUND(2003);

  private final int value;

  private XiaoHaChartErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static XiaoHaChartErrorCode findByValue(int value) { 
    switch (value) {
      case 2000:
        return TAG_NOT_FOUND;
      case 2001:
        return TAG_EXISTS;
      case 2003:
        return CHART_NOT_FOUND;
      default:
        return null;
    }
  }
}
