/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FavoriteChart implements org.apache.thrift.TBase<FavoriteChart, FavoriteChart._Fields>, java.io.Serializable, Cloneable, Comparable<FavoriteChart> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FavoriteChart");

  private static final org.apache.thrift.protocol.TField FAVORITE_CHART_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("favoriteChartId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField XIAOHA_CHART_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("xiaohaChartId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField PARENT_FOLDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("parentFolderId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField PERSONAL_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personalUserId", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FavoriteChartStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FavoriteChartTupleSchemeFactory());
  }

  public long favoriteChartId; // optional
  public long xiaohaChartId; // optional
  public long parentFolderId; // optional
  public long personalUserId; // optional
  public String name; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FAVORITE_CHART_ID((short)1, "favoriteChartId"),
    XIAOHA_CHART_ID((short)2, "xiaohaChartId"),
    PARENT_FOLDER_ID((short)3, "parentFolderId"),
    PERSONAL_USER_ID((short)4, "personalUserId"),
    NAME((short)5, "name");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FAVORITE_CHART_ID
          return FAVORITE_CHART_ID;
        case 2: // XIAOHA_CHART_ID
          return XIAOHA_CHART_ID;
        case 3: // PARENT_FOLDER_ID
          return PARENT_FOLDER_ID;
        case 4: // PERSONAL_USER_ID
          return PERSONAL_USER_ID;
        case 5: // NAME
          return NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FAVORITECHARTID_ISSET_ID = 0;
  private static final int __XIAOHACHARTID_ISSET_ID = 1;
  private static final int __PARENTFOLDERID_ISSET_ID = 2;
  private static final int __PERSONALUSERID_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.FAVORITE_CHART_ID,_Fields.XIAOHA_CHART_ID,_Fields.PARENT_FOLDER_ID,_Fields.PERSONAL_USER_ID,_Fields.NAME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FAVORITE_CHART_ID, new org.apache.thrift.meta_data.FieldMetaData("favoriteChartId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.XIAOHA_CHART_ID, new org.apache.thrift.meta_data.FieldMetaData("xiaohaChartId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PARENT_FOLDER_ID, new org.apache.thrift.meta_data.FieldMetaData("parentFolderId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PERSONAL_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personalUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FavoriteChart.class, metaDataMap);
  }

  public FavoriteChart() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FavoriteChart(FavoriteChart other) {
    __isset_bitfield = other.__isset_bitfield;
    this.favoriteChartId = other.favoriteChartId;
    this.xiaohaChartId = other.xiaohaChartId;
    this.parentFolderId = other.parentFolderId;
    this.personalUserId = other.personalUserId;
    if (other.isSetName()) {
      this.name = other.name;
    }
  }

  public FavoriteChart deepCopy() {
    return new FavoriteChart(this);
  }

  @Override
  public void clear() {
    setFavoriteChartIdIsSet(false);
    this.favoriteChartId = 0;
    setXiaohaChartIdIsSet(false);
    this.xiaohaChartId = 0;
    setParentFolderIdIsSet(false);
    this.parentFolderId = 0;
    setPersonalUserIdIsSet(false);
    this.personalUserId = 0;
    this.name = null;
  }

  public long getFavoriteChartId() {
    return this.favoriteChartId;
  }

  public FavoriteChart setFavoriteChartId(long favoriteChartId) {
    this.favoriteChartId = favoriteChartId;
    setFavoriteChartIdIsSet(true);
    return this;
  }

  public void unsetFavoriteChartId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FAVORITECHARTID_ISSET_ID);
  }

  /** Returns true if field favoriteChartId is set (has been assigned a value) and false otherwise */
  public boolean isSetFavoriteChartId() {
    return EncodingUtils.testBit(__isset_bitfield, __FAVORITECHARTID_ISSET_ID);
  }

  public void setFavoriteChartIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FAVORITECHARTID_ISSET_ID, value);
  }

  public long getXiaohaChartId() {
    return this.xiaohaChartId;
  }

  public FavoriteChart setXiaohaChartId(long xiaohaChartId) {
    this.xiaohaChartId = xiaohaChartId;
    setXiaohaChartIdIsSet(true);
    return this;
  }

  public void unsetXiaohaChartId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID);
  }

  /** Returns true if field xiaohaChartId is set (has been assigned a value) and false otherwise */
  public boolean isSetXiaohaChartId() {
    return EncodingUtils.testBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID);
  }

  public void setXiaohaChartIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID, value);
  }

  public long getParentFolderId() {
    return this.parentFolderId;
  }

  public FavoriteChart setParentFolderId(long parentFolderId) {
    this.parentFolderId = parentFolderId;
    setParentFolderIdIsSet(true);
    return this;
  }

  public void unsetParentFolderId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  /** Returns true if field parentFolderId is set (has been assigned a value) and false otherwise */
  public boolean isSetParentFolderId() {
    return EncodingUtils.testBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  public void setParentFolderIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID, value);
  }

  public long getPersonalUserId() {
    return this.personalUserId;
  }

  public FavoriteChart setPersonalUserId(long personalUserId) {
    this.personalUserId = personalUserId;
    setPersonalUserIdIsSet(true);
    return this;
  }

  public void unsetPersonalUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  /** Returns true if field personalUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonalUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  public void setPersonalUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID, value);
  }

  public String getName() {
    return this.name;
  }

  public FavoriteChart setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FAVORITE_CHART_ID:
      if (value == null) {
        unsetFavoriteChartId();
      } else {
        setFavoriteChartId((Long)value);
      }
      break;

    case XIAOHA_CHART_ID:
      if (value == null) {
        unsetXiaohaChartId();
      } else {
        setXiaohaChartId((Long)value);
      }
      break;

    case PARENT_FOLDER_ID:
      if (value == null) {
        unsetParentFolderId();
      } else {
        setParentFolderId((Long)value);
      }
      break;

    case PERSONAL_USER_ID:
      if (value == null) {
        unsetPersonalUserId();
      } else {
        setPersonalUserId((Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FAVORITE_CHART_ID:
      return Long.valueOf(getFavoriteChartId());

    case XIAOHA_CHART_ID:
      return Long.valueOf(getXiaohaChartId());

    case PARENT_FOLDER_ID:
      return Long.valueOf(getParentFolderId());

    case PERSONAL_USER_ID:
      return Long.valueOf(getPersonalUserId());

    case NAME:
      return getName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FAVORITE_CHART_ID:
      return isSetFavoriteChartId();
    case XIAOHA_CHART_ID:
      return isSetXiaohaChartId();
    case PARENT_FOLDER_ID:
      return isSetParentFolderId();
    case PERSONAL_USER_ID:
      return isSetPersonalUserId();
    case NAME:
      return isSetName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FavoriteChart)
      return this.equals((FavoriteChart)that);
    return false;
  }

  public boolean equals(FavoriteChart that) {
    if (that == null)
      return false;

    boolean this_present_favoriteChartId = true && this.isSetFavoriteChartId();
    boolean that_present_favoriteChartId = true && that.isSetFavoriteChartId();
    if (this_present_favoriteChartId || that_present_favoriteChartId) {
      if (!(this_present_favoriteChartId && that_present_favoriteChartId))
        return false;
      if (this.favoriteChartId != that.favoriteChartId)
        return false;
    }

    boolean this_present_xiaohaChartId = true && this.isSetXiaohaChartId();
    boolean that_present_xiaohaChartId = true && that.isSetXiaohaChartId();
    if (this_present_xiaohaChartId || that_present_xiaohaChartId) {
      if (!(this_present_xiaohaChartId && that_present_xiaohaChartId))
        return false;
      if (this.xiaohaChartId != that.xiaohaChartId)
        return false;
    }

    boolean this_present_parentFolderId = true && this.isSetParentFolderId();
    boolean that_present_parentFolderId = true && that.isSetParentFolderId();
    if (this_present_parentFolderId || that_present_parentFolderId) {
      if (!(this_present_parentFolderId && that_present_parentFolderId))
        return false;
      if (this.parentFolderId != that.parentFolderId)
        return false;
    }

    boolean this_present_personalUserId = true && this.isSetPersonalUserId();
    boolean that_present_personalUserId = true && that.isSetPersonalUserId();
    if (this_present_personalUserId || that_present_personalUserId) {
      if (!(this_present_personalUserId && that_present_personalUserId))
        return false;
      if (this.personalUserId != that.personalUserId)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FavoriteChart other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFavoriteChartId()).compareTo(other.isSetFavoriteChartId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFavoriteChartId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.favoriteChartId, other.favoriteChartId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetXiaohaChartId()).compareTo(other.isSetXiaohaChartId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXiaohaChartId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xiaohaChartId, other.xiaohaChartId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParentFolderId()).compareTo(other.isSetParentFolderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParentFolderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parentFolderId, other.parentFolderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPersonalUserId()).compareTo(other.isSetPersonalUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonalUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personalUserId, other.personalUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FavoriteChart(");
    boolean first = true;

    if (isSetFavoriteChartId()) {
      sb.append("favoriteChartId:");
      sb.append(this.favoriteChartId);
      first = false;
    }
    if (isSetXiaohaChartId()) {
      if (!first) sb.append(", ");
      sb.append("xiaohaChartId:");
      sb.append(this.xiaohaChartId);
      first = false;
    }
    if (isSetParentFolderId()) {
      if (!first) sb.append(", ");
      sb.append("parentFolderId:");
      sb.append(this.parentFolderId);
      first = false;
    }
    if (isSetPersonalUserId()) {
      if (!first) sb.append(", ");
      sb.append("personalUserId:");
      sb.append(this.personalUserId);
      first = false;
    }
    if (isSetName()) {
      if (!first) sb.append(", ");
      sb.append("name:");
      if (this.name == null) {
        sb.append("null");
      } else {
        sb.append(this.name);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FavoriteChartStandardSchemeFactory implements SchemeFactory {
    public FavoriteChartStandardScheme getScheme() {
      return new FavoriteChartStandardScheme();
    }
  }

  private static class FavoriteChartStandardScheme extends StandardScheme<FavoriteChart> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FavoriteChart struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FAVORITE_CHART_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.favoriteChartId = iprot.readI64();
              struct.setFavoriteChartIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // XIAOHA_CHART_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.xiaohaChartId = iprot.readI64();
              struct.setXiaohaChartIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PARENT_FOLDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.parentFolderId = iprot.readI64();
              struct.setParentFolderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PERSONAL_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personalUserId = iprot.readI64();
              struct.setPersonalUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FavoriteChart struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetFavoriteChartId()) {
        oprot.writeFieldBegin(FAVORITE_CHART_ID_FIELD_DESC);
        oprot.writeI64(struct.favoriteChartId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetXiaohaChartId()) {
        oprot.writeFieldBegin(XIAOHA_CHART_ID_FIELD_DESC);
        oprot.writeI64(struct.xiaohaChartId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeFieldBegin(PARENT_FOLDER_ID_FIELD_DESC);
        oprot.writeI64(struct.parentFolderId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPersonalUserId()) {
        oprot.writeFieldBegin(PERSONAL_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personalUserId);
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        if (struct.isSetName()) {
          oprot.writeFieldBegin(NAME_FIELD_DESC);
          oprot.writeString(struct.name);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FavoriteChartTupleSchemeFactory implements SchemeFactory {
    public FavoriteChartTupleScheme getScheme() {
      return new FavoriteChartTupleScheme();
    }
  }

  private static class FavoriteChartTupleScheme extends TupleScheme<FavoriteChart> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FavoriteChart struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFavoriteChartId()) {
        optionals.set(0);
      }
      if (struct.isSetXiaohaChartId()) {
        optionals.set(1);
      }
      if (struct.isSetParentFolderId()) {
        optionals.set(2);
      }
      if (struct.isSetPersonalUserId()) {
        optionals.set(3);
      }
      if (struct.isSetName()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetFavoriteChartId()) {
        oprot.writeI64(struct.favoriteChartId);
      }
      if (struct.isSetXiaohaChartId()) {
        oprot.writeI64(struct.xiaohaChartId);
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeI64(struct.parentFolderId);
      }
      if (struct.isSetPersonalUserId()) {
        oprot.writeI64(struct.personalUserId);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FavoriteChart struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.favoriteChartId = iprot.readI64();
        struct.setFavoriteChartIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.xiaohaChartId = iprot.readI64();
        struct.setXiaohaChartIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.parentFolderId = iprot.readI64();
        struct.setParentFolderIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.personalUserId = iprot.readI64();
        struct.setPersonalUserIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
    }
  }

}

