/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ReqUserRelateInfoOption implements org.apache.thrift.TBase<ReqUserRelateInfoOption, ReqUserRelateInfoOption._Fields>, java.io.Serializable, Cloneable, Comparable<ReqUserRelateInfoOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReqUserRelateInfoOption");

  private static final org.apache.thrift.protocol.TField PERSON_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personUserId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField COMPANY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("companyId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField COMPANY_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("companyUserId", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReqUserRelateInfoOptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReqUserRelateInfoOptionTupleSchemeFactory());
  }

  public long personUserId; // optional
  public long companyId; // optional
  public long companyUserId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PERSON_USER_ID((short)1, "personUserId"),
    COMPANY_ID((short)2, "companyId"),
    COMPANY_USER_ID((short)3, "companyUserId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PERSON_USER_ID
          return PERSON_USER_ID;
        case 2: // COMPANY_ID
          return COMPANY_ID;
        case 3: // COMPANY_USER_ID
          return COMPANY_USER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERSONUSERID_ISSET_ID = 0;
  private static final int __COMPANYID_ISSET_ID = 1;
  private static final int __COMPANYUSERID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.PERSON_USER_ID,_Fields.COMPANY_ID,_Fields.COMPANY_USER_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PERSON_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COMPANY_ID, new org.apache.thrift.meta_data.FieldMetaData("companyId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COMPANY_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("companyUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReqUserRelateInfoOption.class, metaDataMap);
  }

  public ReqUserRelateInfoOption() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReqUserRelateInfoOption(ReqUserRelateInfoOption other) {
    __isset_bitfield = other.__isset_bitfield;
    this.personUserId = other.personUserId;
    this.companyId = other.companyId;
    this.companyUserId = other.companyUserId;
  }

  public ReqUserRelateInfoOption deepCopy() {
    return new ReqUserRelateInfoOption(this);
  }

  @Override
  public void clear() {
    setPersonUserIdIsSet(false);
    this.personUserId = 0;
    setCompanyIdIsSet(false);
    this.companyId = 0;
    setCompanyUserIdIsSet(false);
    this.companyUserId = 0;
  }

  public long getPersonUserId() {
    return this.personUserId;
  }

  public ReqUserRelateInfoOption setPersonUserId(long personUserId) {
    this.personUserId = personUserId;
    setPersonUserIdIsSet(true);
    return this;
  }

  public void unsetPersonUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONUSERID_ISSET_ID);
  }

  /** Returns true if field personUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONUSERID_ISSET_ID);
  }

  public void setPersonUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONUSERID_ISSET_ID, value);
  }

  public long getCompanyId() {
    return this.companyId;
  }

  public ReqUserRelateInfoOption setCompanyId(long companyId) {
    this.companyId = companyId;
    setCompanyIdIsSet(true);
    return this;
  }

  public void unsetCompanyId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMPANYID_ISSET_ID);
  }

  /** Returns true if field companyId is set (has been assigned a value) and false otherwise */
  public boolean isSetCompanyId() {
    return EncodingUtils.testBit(__isset_bitfield, __COMPANYID_ISSET_ID);
  }

  public void setCompanyIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMPANYID_ISSET_ID, value);
  }

  public long getCompanyUserId() {
    return this.companyUserId;
  }

  public ReqUserRelateInfoOption setCompanyUserId(long companyUserId) {
    this.companyUserId = companyUserId;
    setCompanyUserIdIsSet(true);
    return this;
  }

  public void unsetCompanyUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID);
  }

  /** Returns true if field companyUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetCompanyUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID);
  }

  public void setCompanyUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PERSON_USER_ID:
      if (value == null) {
        unsetPersonUserId();
      } else {
        setPersonUserId((Long)value);
      }
      break;

    case COMPANY_ID:
      if (value == null) {
        unsetCompanyId();
      } else {
        setCompanyId((Long)value);
      }
      break;

    case COMPANY_USER_ID:
      if (value == null) {
        unsetCompanyUserId();
      } else {
        setCompanyUserId((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PERSON_USER_ID:
      return Long.valueOf(getPersonUserId());

    case COMPANY_ID:
      return Long.valueOf(getCompanyId());

    case COMPANY_USER_ID:
      return Long.valueOf(getCompanyUserId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PERSON_USER_ID:
      return isSetPersonUserId();
    case COMPANY_ID:
      return isSetCompanyId();
    case COMPANY_USER_ID:
      return isSetCompanyUserId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReqUserRelateInfoOption)
      return this.equals((ReqUserRelateInfoOption)that);
    return false;
  }

  public boolean equals(ReqUserRelateInfoOption that) {
    if (that == null)
      return false;

    boolean this_present_personUserId = true && this.isSetPersonUserId();
    boolean that_present_personUserId = true && that.isSetPersonUserId();
    if (this_present_personUserId || that_present_personUserId) {
      if (!(this_present_personUserId && that_present_personUserId))
        return false;
      if (this.personUserId != that.personUserId)
        return false;
    }

    boolean this_present_companyId = true && this.isSetCompanyId();
    boolean that_present_companyId = true && that.isSetCompanyId();
    if (this_present_companyId || that_present_companyId) {
      if (!(this_present_companyId && that_present_companyId))
        return false;
      if (this.companyId != that.companyId)
        return false;
    }

    boolean this_present_companyUserId = true && this.isSetCompanyUserId();
    boolean that_present_companyUserId = true && that.isSetCompanyUserId();
    if (this_present_companyUserId || that_present_companyUserId) {
      if (!(this_present_companyUserId && that_present_companyUserId))
        return false;
      if (this.companyUserId != that.companyUserId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ReqUserRelateInfoOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPersonUserId()).compareTo(other.isSetPersonUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personUserId, other.personUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCompanyId()).compareTo(other.isSetCompanyId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompanyId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyId, other.companyId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCompanyUserId()).compareTo(other.isSetCompanyUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompanyUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyUserId, other.companyUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReqUserRelateInfoOption(");
    boolean first = true;

    if (isSetPersonUserId()) {
      sb.append("personUserId:");
      sb.append(this.personUserId);
      first = false;
    }
    if (isSetCompanyId()) {
      if (!first) sb.append(", ");
      sb.append("companyId:");
      sb.append(this.companyId);
      first = false;
    }
    if (isSetCompanyUserId()) {
      if (!first) sb.append(", ");
      sb.append("companyUserId:");
      sb.append(this.companyUserId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReqUserRelateInfoOptionStandardSchemeFactory implements SchemeFactory {
    public ReqUserRelateInfoOptionStandardScheme getScheme() {
      return new ReqUserRelateInfoOptionStandardScheme();
    }
  }

  private static class ReqUserRelateInfoOptionStandardScheme extends StandardScheme<ReqUserRelateInfoOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReqUserRelateInfoOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PERSON_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personUserId = iprot.readI64();
              struct.setPersonUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMPANY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.companyId = iprot.readI64();
              struct.setCompanyIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMPANY_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.companyUserId = iprot.readI64();
              struct.setCompanyUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReqUserRelateInfoOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetPersonUserId()) {
        oprot.writeFieldBegin(PERSON_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personUserId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCompanyId()) {
        oprot.writeFieldBegin(COMPANY_ID_FIELD_DESC);
        oprot.writeI64(struct.companyId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCompanyUserId()) {
        oprot.writeFieldBegin(COMPANY_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.companyUserId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReqUserRelateInfoOptionTupleSchemeFactory implements SchemeFactory {
    public ReqUserRelateInfoOptionTupleScheme getScheme() {
      return new ReqUserRelateInfoOptionTupleScheme();
    }
  }

  private static class ReqUserRelateInfoOptionTupleScheme extends TupleScheme<ReqUserRelateInfoOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReqUserRelateInfoOption struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPersonUserId()) {
        optionals.set(0);
      }
      if (struct.isSetCompanyId()) {
        optionals.set(1);
      }
      if (struct.isSetCompanyUserId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPersonUserId()) {
        oprot.writeI64(struct.personUserId);
      }
      if (struct.isSetCompanyId()) {
        oprot.writeI64(struct.companyId);
      }
      if (struct.isSetCompanyUserId()) {
        oprot.writeI64(struct.companyUserId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReqUserRelateInfoOption struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.personUserId = iprot.readI64();
        struct.setPersonUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.companyId = iprot.readI64();
        struct.setCompanyIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.companyUserId = iprot.readI64();
        struct.setCompanyUserIdIsSet(true);
      }
    }
  }

}

