/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserRelateInfo implements org.apache.thrift.TBase<UserRelateInfo, UserRelateInfo._Fields>, java.io.Serializable, Cloneable, Comparable<UserRelateInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserRelateInfo");

  private static final org.apache.thrift.protocol.TField PERSONAL_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personalUserId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField COMPANY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("companyId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField COMPANY_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("companyUserId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField CREATE_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("createTimestamp", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField LAST_MODIFY_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("lastModifyTimestamp", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField LINKED_FIELD_DESC = new org.apache.thrift.protocol.TField("linked", org.apache.thrift.protocol.TType.BOOL, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserRelateInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserRelateInfoTupleSchemeFactory());
  }

  public long personalUserId; // optional
  public long companyId; // optional
  public long companyUserId; // optional
  public long createTimestamp; // optional
  public long lastModifyTimestamp; // optional
  public boolean linked; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PERSONAL_USER_ID((short)1, "personalUserId"),
    COMPANY_ID((short)2, "companyId"),
    COMPANY_USER_ID((short)3, "companyUserId"),
    CREATE_TIMESTAMP((short)4, "createTimestamp"),
    LAST_MODIFY_TIMESTAMP((short)5, "lastModifyTimestamp"),
    LINKED((short)6, "linked");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PERSONAL_USER_ID
          return PERSONAL_USER_ID;
        case 2: // COMPANY_ID
          return COMPANY_ID;
        case 3: // COMPANY_USER_ID
          return COMPANY_USER_ID;
        case 4: // CREATE_TIMESTAMP
          return CREATE_TIMESTAMP;
        case 5: // LAST_MODIFY_TIMESTAMP
          return LAST_MODIFY_TIMESTAMP;
        case 6: // LINKED
          return LINKED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERSONALUSERID_ISSET_ID = 0;
  private static final int __COMPANYID_ISSET_ID = 1;
  private static final int __COMPANYUSERID_ISSET_ID = 2;
  private static final int __CREATETIMESTAMP_ISSET_ID = 3;
  private static final int __LASTMODIFYTIMESTAMP_ISSET_ID = 4;
  private static final int __LINKED_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.PERSONAL_USER_ID,_Fields.COMPANY_ID,_Fields.COMPANY_USER_ID,_Fields.CREATE_TIMESTAMP,_Fields.LAST_MODIFY_TIMESTAMP,_Fields.LINKED};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PERSONAL_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personalUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COMPANY_ID, new org.apache.thrift.meta_data.FieldMetaData("companyId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COMPANY_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("companyUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATE_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("createTimestamp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_MODIFY_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("lastModifyTimestamp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LINKED, new org.apache.thrift.meta_data.FieldMetaData("linked", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserRelateInfo.class, metaDataMap);
  }

  public UserRelateInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserRelateInfo(UserRelateInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.personalUserId = other.personalUserId;
    this.companyId = other.companyId;
    this.companyUserId = other.companyUserId;
    this.createTimestamp = other.createTimestamp;
    this.lastModifyTimestamp = other.lastModifyTimestamp;
    this.linked = other.linked;
  }

  public UserRelateInfo deepCopy() {
    return new UserRelateInfo(this);
  }

  @Override
  public void clear() {
    setPersonalUserIdIsSet(false);
    this.personalUserId = 0;
    setCompanyIdIsSet(false);
    this.companyId = 0;
    setCompanyUserIdIsSet(false);
    this.companyUserId = 0;
    setCreateTimestampIsSet(false);
    this.createTimestamp = 0;
    setLastModifyTimestampIsSet(false);
    this.lastModifyTimestamp = 0;
    setLinkedIsSet(false);
    this.linked = false;
  }

  public long getPersonalUserId() {
    return this.personalUserId;
  }

  public UserRelateInfo setPersonalUserId(long personalUserId) {
    this.personalUserId = personalUserId;
    setPersonalUserIdIsSet(true);
    return this;
  }

  public void unsetPersonalUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  /** Returns true if field personalUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonalUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  public void setPersonalUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID, value);
  }

  public long getCompanyId() {
    return this.companyId;
  }

  public UserRelateInfo setCompanyId(long companyId) {
    this.companyId = companyId;
    setCompanyIdIsSet(true);
    return this;
  }

  public void unsetCompanyId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMPANYID_ISSET_ID);
  }

  /** Returns true if field companyId is set (has been assigned a value) and false otherwise */
  public boolean isSetCompanyId() {
    return EncodingUtils.testBit(__isset_bitfield, __COMPANYID_ISSET_ID);
  }

  public void setCompanyIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMPANYID_ISSET_ID, value);
  }

  public long getCompanyUserId() {
    return this.companyUserId;
  }

  public UserRelateInfo setCompanyUserId(long companyUserId) {
    this.companyUserId = companyUserId;
    setCompanyUserIdIsSet(true);
    return this;
  }

  public void unsetCompanyUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID);
  }

  /** Returns true if field companyUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetCompanyUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID);
  }

  public void setCompanyUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMPANYUSERID_ISSET_ID, value);
  }

  public long getCreateTimestamp() {
    return this.createTimestamp;
  }

  public UserRelateInfo setCreateTimestamp(long createTimestamp) {
    this.createTimestamp = createTimestamp;
    setCreateTimestampIsSet(true);
    return this;
  }

  public void unsetCreateTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATETIMESTAMP_ISSET_ID);
  }

  /** Returns true if field createTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATETIMESTAMP_ISSET_ID);
  }

  public void setCreateTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATETIMESTAMP_ISSET_ID, value);
  }

  public long getLastModifyTimestamp() {
    return this.lastModifyTimestamp;
  }

  public UserRelateInfo setLastModifyTimestamp(long lastModifyTimestamp) {
    this.lastModifyTimestamp = lastModifyTimestamp;
    setLastModifyTimestampIsSet(true);
    return this;
  }

  public void unsetLastModifyTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTMODIFYTIMESTAMP_ISSET_ID);
  }

  /** Returns true if field lastModifyTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetLastModifyTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTMODIFYTIMESTAMP_ISSET_ID);
  }

  public void setLastModifyTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTMODIFYTIMESTAMP_ISSET_ID, value);
  }

  public boolean isLinked() {
    return this.linked;
  }

  public UserRelateInfo setLinked(boolean linked) {
    this.linked = linked;
    setLinkedIsSet(true);
    return this;
  }

  public void unsetLinked() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LINKED_ISSET_ID);
  }

  /** Returns true if field linked is set (has been assigned a value) and false otherwise */
  public boolean isSetLinked() {
    return EncodingUtils.testBit(__isset_bitfield, __LINKED_ISSET_ID);
  }

  public void setLinkedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LINKED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PERSONAL_USER_ID:
      if (value == null) {
        unsetPersonalUserId();
      } else {
        setPersonalUserId((Long)value);
      }
      break;

    case COMPANY_ID:
      if (value == null) {
        unsetCompanyId();
      } else {
        setCompanyId((Long)value);
      }
      break;

    case COMPANY_USER_ID:
      if (value == null) {
        unsetCompanyUserId();
      } else {
        setCompanyUserId((Long)value);
      }
      break;

    case CREATE_TIMESTAMP:
      if (value == null) {
        unsetCreateTimestamp();
      } else {
        setCreateTimestamp((Long)value);
      }
      break;

    case LAST_MODIFY_TIMESTAMP:
      if (value == null) {
        unsetLastModifyTimestamp();
      } else {
        setLastModifyTimestamp((Long)value);
      }
      break;

    case LINKED:
      if (value == null) {
        unsetLinked();
      } else {
        setLinked((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PERSONAL_USER_ID:
      return Long.valueOf(getPersonalUserId());

    case COMPANY_ID:
      return Long.valueOf(getCompanyId());

    case COMPANY_USER_ID:
      return Long.valueOf(getCompanyUserId());

    case CREATE_TIMESTAMP:
      return Long.valueOf(getCreateTimestamp());

    case LAST_MODIFY_TIMESTAMP:
      return Long.valueOf(getLastModifyTimestamp());

    case LINKED:
      return Boolean.valueOf(isLinked());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PERSONAL_USER_ID:
      return isSetPersonalUserId();
    case COMPANY_ID:
      return isSetCompanyId();
    case COMPANY_USER_ID:
      return isSetCompanyUserId();
    case CREATE_TIMESTAMP:
      return isSetCreateTimestamp();
    case LAST_MODIFY_TIMESTAMP:
      return isSetLastModifyTimestamp();
    case LINKED:
      return isSetLinked();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserRelateInfo)
      return this.equals((UserRelateInfo)that);
    return false;
  }

  public boolean equals(UserRelateInfo that) {
    if (that == null)
      return false;

    boolean this_present_personalUserId = true && this.isSetPersonalUserId();
    boolean that_present_personalUserId = true && that.isSetPersonalUserId();
    if (this_present_personalUserId || that_present_personalUserId) {
      if (!(this_present_personalUserId && that_present_personalUserId))
        return false;
      if (this.personalUserId != that.personalUserId)
        return false;
    }

    boolean this_present_companyId = true && this.isSetCompanyId();
    boolean that_present_companyId = true && that.isSetCompanyId();
    if (this_present_companyId || that_present_companyId) {
      if (!(this_present_companyId && that_present_companyId))
        return false;
      if (this.companyId != that.companyId)
        return false;
    }

    boolean this_present_companyUserId = true && this.isSetCompanyUserId();
    boolean that_present_companyUserId = true && that.isSetCompanyUserId();
    if (this_present_companyUserId || that_present_companyUserId) {
      if (!(this_present_companyUserId && that_present_companyUserId))
        return false;
      if (this.companyUserId != that.companyUserId)
        return false;
    }

    boolean this_present_createTimestamp = true && this.isSetCreateTimestamp();
    boolean that_present_createTimestamp = true && that.isSetCreateTimestamp();
    if (this_present_createTimestamp || that_present_createTimestamp) {
      if (!(this_present_createTimestamp && that_present_createTimestamp))
        return false;
      if (this.createTimestamp != that.createTimestamp)
        return false;
    }

    boolean this_present_lastModifyTimestamp = true && this.isSetLastModifyTimestamp();
    boolean that_present_lastModifyTimestamp = true && that.isSetLastModifyTimestamp();
    if (this_present_lastModifyTimestamp || that_present_lastModifyTimestamp) {
      if (!(this_present_lastModifyTimestamp && that_present_lastModifyTimestamp))
        return false;
      if (this.lastModifyTimestamp != that.lastModifyTimestamp)
        return false;
    }

    boolean this_present_linked = true && this.isSetLinked();
    boolean that_present_linked = true && that.isSetLinked();
    if (this_present_linked || that_present_linked) {
      if (!(this_present_linked && that_present_linked))
        return false;
      if (this.linked != that.linked)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(UserRelateInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPersonalUserId()).compareTo(other.isSetPersonalUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonalUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personalUserId, other.personalUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCompanyId()).compareTo(other.isSetCompanyId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompanyId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyId, other.companyId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCompanyUserId()).compareTo(other.isSetCompanyUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompanyUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyUserId, other.companyUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTimestamp()).compareTo(other.isSetCreateTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTimestamp, other.createTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastModifyTimestamp()).compareTo(other.isSetLastModifyTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastModifyTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastModifyTimestamp, other.lastModifyTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLinked()).compareTo(other.isSetLinked());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLinked()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.linked, other.linked);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserRelateInfo(");
    boolean first = true;

    if (isSetPersonalUserId()) {
      sb.append("personalUserId:");
      sb.append(this.personalUserId);
      first = false;
    }
    if (isSetCompanyId()) {
      if (!first) sb.append(", ");
      sb.append("companyId:");
      sb.append(this.companyId);
      first = false;
    }
    if (isSetCompanyUserId()) {
      if (!first) sb.append(", ");
      sb.append("companyUserId:");
      sb.append(this.companyUserId);
      first = false;
    }
    if (isSetCreateTimestamp()) {
      if (!first) sb.append(", ");
      sb.append("createTimestamp:");
      sb.append(this.createTimestamp);
      first = false;
    }
    if (isSetLastModifyTimestamp()) {
      if (!first) sb.append(", ");
      sb.append("lastModifyTimestamp:");
      sb.append(this.lastModifyTimestamp);
      first = false;
    }
    if (isSetLinked()) {
      if (!first) sb.append(", ");
      sb.append("linked:");
      sb.append(this.linked);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserRelateInfoStandardSchemeFactory implements SchemeFactory {
    public UserRelateInfoStandardScheme getScheme() {
      return new UserRelateInfoStandardScheme();
    }
  }

  private static class UserRelateInfoStandardScheme extends StandardScheme<UserRelateInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserRelateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PERSONAL_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personalUserId = iprot.readI64();
              struct.setPersonalUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMPANY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.companyId = iprot.readI64();
              struct.setCompanyIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMPANY_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.companyUserId = iprot.readI64();
              struct.setCompanyUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CREATE_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTimestamp = iprot.readI64();
              struct.setCreateTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LAST_MODIFY_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastModifyTimestamp = iprot.readI64();
              struct.setLastModifyTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LINKED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.linked = iprot.readBool();
              struct.setLinkedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserRelateInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetPersonalUserId()) {
        oprot.writeFieldBegin(PERSONAL_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personalUserId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCompanyId()) {
        oprot.writeFieldBegin(COMPANY_ID_FIELD_DESC);
        oprot.writeI64(struct.companyId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCompanyUserId()) {
        oprot.writeFieldBegin(COMPANY_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.companyUserId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCreateTimestamp()) {
        oprot.writeFieldBegin(CREATE_TIMESTAMP_FIELD_DESC);
        oprot.writeI64(struct.createTimestamp);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLastModifyTimestamp()) {
        oprot.writeFieldBegin(LAST_MODIFY_TIMESTAMP_FIELD_DESC);
        oprot.writeI64(struct.lastModifyTimestamp);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLinked()) {
        oprot.writeFieldBegin(LINKED_FIELD_DESC);
        oprot.writeBool(struct.linked);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserRelateInfoTupleSchemeFactory implements SchemeFactory {
    public UserRelateInfoTupleScheme getScheme() {
      return new UserRelateInfoTupleScheme();
    }
  }

  private static class UserRelateInfoTupleScheme extends TupleScheme<UserRelateInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserRelateInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPersonalUserId()) {
        optionals.set(0);
      }
      if (struct.isSetCompanyId()) {
        optionals.set(1);
      }
      if (struct.isSetCompanyUserId()) {
        optionals.set(2);
      }
      if (struct.isSetCreateTimestamp()) {
        optionals.set(3);
      }
      if (struct.isSetLastModifyTimestamp()) {
        optionals.set(4);
      }
      if (struct.isSetLinked()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetPersonalUserId()) {
        oprot.writeI64(struct.personalUserId);
      }
      if (struct.isSetCompanyId()) {
        oprot.writeI64(struct.companyId);
      }
      if (struct.isSetCompanyUserId()) {
        oprot.writeI64(struct.companyUserId);
      }
      if (struct.isSetCreateTimestamp()) {
        oprot.writeI64(struct.createTimestamp);
      }
      if (struct.isSetLastModifyTimestamp()) {
        oprot.writeI64(struct.lastModifyTimestamp);
      }
      if (struct.isSetLinked()) {
        oprot.writeBool(struct.linked);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserRelateInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.personalUserId = iprot.readI64();
        struct.setPersonalUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.companyId = iprot.readI64();
        struct.setCompanyIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.companyUserId = iprot.readI64();
        struct.setCompanyUserIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.createTimestamp = iprot.readI64();
        struct.setCreateTimestampIsSet(true);
      }
      if (incoming.get(4)) {
        struct.lastModifyTimestamp = iprot.readI64();
        struct.setLastModifyTimestampIsSet(true);
      }
      if (incoming.get(5)) {
        struct.linked = iprot.readBool();
        struct.setLinkedIsSet(true);
      }
    }
  }

}

