/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.graph.xiaoha.chart.terminal.ao.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LinkState implements org.apache.thrift.TEnum {
  UN_LINKED(0),
  LINKED(1);

  private final int value;

  private LinkState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LinkState findByValue(int value) { 
    switch (value) {
      case 0:
        return UN_LINKED;
      case 1:
        return LINKED;
      default:
        return null;
    }
  }
}
