/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.graph.xiaoha.chart.terminal.ao.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 登陆信息
 */
public class XiaohaChartLandingInfo implements org.apache.thrift.TBase<XiaohaChartLandingInfo, XiaohaChartLandingInfo._Fields>, java.io.Serializable, Cloneable, Comparable<XiaohaChartLandingInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("XiaohaChartLandingInfo");

  private static final org.apache.thrift.protocol.TField PERSONAL_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personalUserId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("token", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new XiaohaChartLandingInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new XiaohaChartLandingInfoTupleSchemeFactory());
  }

  public long personalUserId; // optional
  public String token; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PERSONAL_USER_ID((short)1, "personalUserId"),
    TOKEN((short)2, "token");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PERSONAL_USER_ID
          return PERSONAL_USER_ID;
        case 2: // TOKEN
          return TOKEN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERSONALUSERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.PERSONAL_USER_ID,_Fields.TOKEN};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PERSONAL_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personalUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TOKEN, new org.apache.thrift.meta_data.FieldMetaData("token", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(XiaohaChartLandingInfo.class, metaDataMap);
  }

  public XiaohaChartLandingInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public XiaohaChartLandingInfo(XiaohaChartLandingInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.personalUserId = other.personalUserId;
    if (other.isSetToken()) {
      this.token = other.token;
    }
  }

  public XiaohaChartLandingInfo deepCopy() {
    return new XiaohaChartLandingInfo(this);
  }

  @Override
  public void clear() {
    setPersonalUserIdIsSet(false);
    this.personalUserId = 0;
    this.token = null;
  }

  public long getPersonalUserId() {
    return this.personalUserId;
  }

  public XiaohaChartLandingInfo setPersonalUserId(long personalUserId) {
    this.personalUserId = personalUserId;
    setPersonalUserIdIsSet(true);
    return this;
  }

  public void unsetPersonalUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  /** Returns true if field personalUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonalUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  public void setPersonalUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID, value);
  }

  public String getToken() {
    return this.token;
  }

  public XiaohaChartLandingInfo setToken(String token) {
    this.token = token;
    return this;
  }

  public void unsetToken() {
    this.token = null;
  }

  /** Returns true if field token is set (has been assigned a value) and false otherwise */
  public boolean isSetToken() {
    return this.token != null;
  }

  public void setTokenIsSet(boolean value) {
    if (!value) {
      this.token = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PERSONAL_USER_ID:
      if (value == null) {
        unsetPersonalUserId();
      } else {
        setPersonalUserId((Long)value);
      }
      break;

    case TOKEN:
      if (value == null) {
        unsetToken();
      } else {
        setToken((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PERSONAL_USER_ID:
      return Long.valueOf(getPersonalUserId());

    case TOKEN:
      return getToken();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PERSONAL_USER_ID:
      return isSetPersonalUserId();
    case TOKEN:
      return isSetToken();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof XiaohaChartLandingInfo)
      return this.equals((XiaohaChartLandingInfo)that);
    return false;
  }

  public boolean equals(XiaohaChartLandingInfo that) {
    if (that == null)
      return false;

    boolean this_present_personalUserId = true && this.isSetPersonalUserId();
    boolean that_present_personalUserId = true && that.isSetPersonalUserId();
    if (this_present_personalUserId || that_present_personalUserId) {
      if (!(this_present_personalUserId && that_present_personalUserId))
        return false;
      if (this.personalUserId != that.personalUserId)
        return false;
    }

    boolean this_present_token = true && this.isSetToken();
    boolean that_present_token = true && that.isSetToken();
    if (this_present_token || that_present_token) {
      if (!(this_present_token && that_present_token))
        return false;
      if (!this.token.equals(that.token))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(XiaohaChartLandingInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPersonalUserId()).compareTo(other.isSetPersonalUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonalUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personalUserId, other.personalUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetToken()).compareTo(other.isSetToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.token, other.token);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("XiaohaChartLandingInfo(");
    boolean first = true;

    if (isSetPersonalUserId()) {
      sb.append("personalUserId:");
      sb.append(this.personalUserId);
      first = false;
    }
    if (isSetToken()) {
      if (!first) sb.append(", ");
      sb.append("token:");
      if (this.token == null) {
        sb.append("null");
      } else {
        sb.append(this.token);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class XiaohaChartLandingInfoStandardSchemeFactory implements SchemeFactory {
    public XiaohaChartLandingInfoStandardScheme getScheme() {
      return new XiaohaChartLandingInfoStandardScheme();
    }
  }

  private static class XiaohaChartLandingInfoStandardScheme extends StandardScheme<XiaohaChartLandingInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, XiaohaChartLandingInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PERSONAL_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personalUserId = iprot.readI64();
              struct.setPersonalUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.token = iprot.readString();
              struct.setTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, XiaohaChartLandingInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetPersonalUserId()) {
        oprot.writeFieldBegin(PERSONAL_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personalUserId);
        oprot.writeFieldEnd();
      }
      if (struct.token != null) {
        if (struct.isSetToken()) {
          oprot.writeFieldBegin(TOKEN_FIELD_DESC);
          oprot.writeString(struct.token);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class XiaohaChartLandingInfoTupleSchemeFactory implements SchemeFactory {
    public XiaohaChartLandingInfoTupleScheme getScheme() {
      return new XiaohaChartLandingInfoTupleScheme();
    }
  }

  private static class XiaohaChartLandingInfoTupleScheme extends TupleScheme<XiaohaChartLandingInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, XiaohaChartLandingInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPersonalUserId()) {
        optionals.set(0);
      }
      if (struct.isSetToken()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPersonalUserId()) {
        oprot.writeI64(struct.personalUserId);
      }
      if (struct.isSetToken()) {
        oprot.writeString(struct.token);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, XiaohaChartLandingInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.personalUserId = iprot.readI64();
        struct.setPersonalUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.token = iprot.readString();
        struct.setTokenIsSet(true);
      }
    }
  }

}

