/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.graph.xiaoha.chart.terminal.ao.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum XiaohaChartTerminalError implements org.apache.thrift.TEnum {
  SESSION_ERROR(3000),
  SESSION_TIMEOUT(3001),
  SESSION_DIFFERENT(3002),
  LOGIN_TEL_NOT_FOUND(3003),
  VERIFY_CODE_ERROR(3004);

  private final int value;

  private XiaohaChartTerminalError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static XiaohaChartTerminalError findByValue(int value) { 
    switch (value) {
      case 3000:
        return SESSION_ERROR;
      case 3001:
        return SESSION_TIMEOUT;
      case 3002:
        return SESSION_DIFFERENT;
      case 3003:
        return LOGIN_TEL_NOT_FOUND;
      case 3004:
        return VERIFY_CODE_ERROR;
      default:
        return null;
    }
  }
}
