/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FavoriteFolder implements org.apache.thrift.TBase<FavoriteFolder, FavoriteFolder._Fields>, java.io.Serializable, Cloneable, Comparable<FavoriteFolder> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FavoriteFolder");

  private static final org.apache.thrift.protocol.TField FOLDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("folderId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField FOLDER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("folderName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PARENT_FOLDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("parentFolderId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField PERSONAL_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personalUserId", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FavoriteFolderStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FavoriteFolderTupleSchemeFactory());
  }

  public long folderId; // optional
  public String folderName; // optional
  public long parentFolderId; // optional
  public long personalUserId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FOLDER_ID((short)1, "folderId"),
    FOLDER_NAME((short)2, "folderName"),
    PARENT_FOLDER_ID((short)3, "parentFolderId"),
    PERSONAL_USER_ID((short)4, "personalUserId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FOLDER_ID
          return FOLDER_ID;
        case 2: // FOLDER_NAME
          return FOLDER_NAME;
        case 3: // PARENT_FOLDER_ID
          return PARENT_FOLDER_ID;
        case 4: // PERSONAL_USER_ID
          return PERSONAL_USER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FOLDERID_ISSET_ID = 0;
  private static final int __PARENTFOLDERID_ISSET_ID = 1;
  private static final int __PERSONALUSERID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.FOLDER_ID,_Fields.FOLDER_NAME,_Fields.PARENT_FOLDER_ID,_Fields.PERSONAL_USER_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FOLDER_ID, new org.apache.thrift.meta_data.FieldMetaData("folderId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FOLDER_NAME, new org.apache.thrift.meta_data.FieldMetaData("folderName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARENT_FOLDER_ID, new org.apache.thrift.meta_data.FieldMetaData("parentFolderId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PERSONAL_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personalUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FavoriteFolder.class, metaDataMap);
  }

  public FavoriteFolder() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FavoriteFolder(FavoriteFolder other) {
    __isset_bitfield = other.__isset_bitfield;
    this.folderId = other.folderId;
    if (other.isSetFolderName()) {
      this.folderName = other.folderName;
    }
    this.parentFolderId = other.parentFolderId;
    this.personalUserId = other.personalUserId;
  }

  public FavoriteFolder deepCopy() {
    return new FavoriteFolder(this);
  }

  @Override
  public void clear() {
    setFolderIdIsSet(false);
    this.folderId = 0;
    this.folderName = null;
    setParentFolderIdIsSet(false);
    this.parentFolderId = 0;
    setPersonalUserIdIsSet(false);
    this.personalUserId = 0;
  }

  public long getFolderId() {
    return this.folderId;
  }

  public FavoriteFolder setFolderId(long folderId) {
    this.folderId = folderId;
    setFolderIdIsSet(true);
    return this;
  }

  public void unsetFolderId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FOLDERID_ISSET_ID);
  }

  /** Returns true if field folderId is set (has been assigned a value) and false otherwise */
  public boolean isSetFolderId() {
    return EncodingUtils.testBit(__isset_bitfield, __FOLDERID_ISSET_ID);
  }

  public void setFolderIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FOLDERID_ISSET_ID, value);
  }

  public String getFolderName() {
    return this.folderName;
  }

  public FavoriteFolder setFolderName(String folderName) {
    this.folderName = folderName;
    return this;
  }

  public void unsetFolderName() {
    this.folderName = null;
  }

  /** Returns true if field folderName is set (has been assigned a value) and false otherwise */
  public boolean isSetFolderName() {
    return this.folderName != null;
  }

  public void setFolderNameIsSet(boolean value) {
    if (!value) {
      this.folderName = null;
    }
  }

  public long getParentFolderId() {
    return this.parentFolderId;
  }

  public FavoriteFolder setParentFolderId(long parentFolderId) {
    this.parentFolderId = parentFolderId;
    setParentFolderIdIsSet(true);
    return this;
  }

  public void unsetParentFolderId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  /** Returns true if field parentFolderId is set (has been assigned a value) and false otherwise */
  public boolean isSetParentFolderId() {
    return EncodingUtils.testBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  public void setParentFolderIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID, value);
  }

  public long getPersonalUserId() {
    return this.personalUserId;
  }

  public FavoriteFolder setPersonalUserId(long personalUserId) {
    this.personalUserId = personalUserId;
    setPersonalUserIdIsSet(true);
    return this;
  }

  public void unsetPersonalUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  /** Returns true if field personalUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonalUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID);
  }

  public void setPersonalUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONALUSERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FOLDER_ID:
      if (value == null) {
        unsetFolderId();
      } else {
        setFolderId((Long)value);
      }
      break;

    case FOLDER_NAME:
      if (value == null) {
        unsetFolderName();
      } else {
        setFolderName((String)value);
      }
      break;

    case PARENT_FOLDER_ID:
      if (value == null) {
        unsetParentFolderId();
      } else {
        setParentFolderId((Long)value);
      }
      break;

    case PERSONAL_USER_ID:
      if (value == null) {
        unsetPersonalUserId();
      } else {
        setPersonalUserId((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FOLDER_ID:
      return Long.valueOf(getFolderId());

    case FOLDER_NAME:
      return getFolderName();

    case PARENT_FOLDER_ID:
      return Long.valueOf(getParentFolderId());

    case PERSONAL_USER_ID:
      return Long.valueOf(getPersonalUserId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FOLDER_ID:
      return isSetFolderId();
    case FOLDER_NAME:
      return isSetFolderName();
    case PARENT_FOLDER_ID:
      return isSetParentFolderId();
    case PERSONAL_USER_ID:
      return isSetPersonalUserId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FavoriteFolder)
      return this.equals((FavoriteFolder)that);
    return false;
  }

  public boolean equals(FavoriteFolder that) {
    if (that == null)
      return false;

    boolean this_present_folderId = true && this.isSetFolderId();
    boolean that_present_folderId = true && that.isSetFolderId();
    if (this_present_folderId || that_present_folderId) {
      if (!(this_present_folderId && that_present_folderId))
        return false;
      if (this.folderId != that.folderId)
        return false;
    }

    boolean this_present_folderName = true && this.isSetFolderName();
    boolean that_present_folderName = true && that.isSetFolderName();
    if (this_present_folderName || that_present_folderName) {
      if (!(this_present_folderName && that_present_folderName))
        return false;
      if (!this.folderName.equals(that.folderName))
        return false;
    }

    boolean this_present_parentFolderId = true && this.isSetParentFolderId();
    boolean that_present_parentFolderId = true && that.isSetParentFolderId();
    if (this_present_parentFolderId || that_present_parentFolderId) {
      if (!(this_present_parentFolderId && that_present_parentFolderId))
        return false;
      if (this.parentFolderId != that.parentFolderId)
        return false;
    }

    boolean this_present_personalUserId = true && this.isSetPersonalUserId();
    boolean that_present_personalUserId = true && that.isSetPersonalUserId();
    if (this_present_personalUserId || that_present_personalUserId) {
      if (!(this_present_personalUserId && that_present_personalUserId))
        return false;
      if (this.personalUserId != that.personalUserId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FavoriteFolder other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFolderId()).compareTo(other.isSetFolderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFolderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.folderId, other.folderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFolderName()).compareTo(other.isSetFolderName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFolderName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.folderName, other.folderName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParentFolderId()).compareTo(other.isSetParentFolderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParentFolderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parentFolderId, other.parentFolderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPersonalUserId()).compareTo(other.isSetPersonalUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonalUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personalUserId, other.personalUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FavoriteFolder(");
    boolean first = true;

    if (isSetFolderId()) {
      sb.append("folderId:");
      sb.append(this.folderId);
      first = false;
    }
    if (isSetFolderName()) {
      if (!first) sb.append(", ");
      sb.append("folderName:");
      if (this.folderName == null) {
        sb.append("null");
      } else {
        sb.append(this.folderName);
      }
      first = false;
    }
    if (isSetParentFolderId()) {
      if (!first) sb.append(", ");
      sb.append("parentFolderId:");
      sb.append(this.parentFolderId);
      first = false;
    }
    if (isSetPersonalUserId()) {
      if (!first) sb.append(", ");
      sb.append("personalUserId:");
      sb.append(this.personalUserId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FavoriteFolderStandardSchemeFactory implements SchemeFactory {
    public FavoriteFolderStandardScheme getScheme() {
      return new FavoriteFolderStandardScheme();
    }
  }

  private static class FavoriteFolderStandardScheme extends StandardScheme<FavoriteFolder> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FavoriteFolder struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FOLDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.folderId = iprot.readI64();
              struct.setFolderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FOLDER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.folderName = iprot.readString();
              struct.setFolderNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PARENT_FOLDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.parentFolderId = iprot.readI64();
              struct.setParentFolderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PERSONAL_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personalUserId = iprot.readI64();
              struct.setPersonalUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FavoriteFolder struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetFolderId()) {
        oprot.writeFieldBegin(FOLDER_ID_FIELD_DESC);
        oprot.writeI64(struct.folderId);
        oprot.writeFieldEnd();
      }
      if (struct.folderName != null) {
        if (struct.isSetFolderName()) {
          oprot.writeFieldBegin(FOLDER_NAME_FIELD_DESC);
          oprot.writeString(struct.folderName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeFieldBegin(PARENT_FOLDER_ID_FIELD_DESC);
        oprot.writeI64(struct.parentFolderId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPersonalUserId()) {
        oprot.writeFieldBegin(PERSONAL_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personalUserId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FavoriteFolderTupleSchemeFactory implements SchemeFactory {
    public FavoriteFolderTupleScheme getScheme() {
      return new FavoriteFolderTupleScheme();
    }
  }

  private static class FavoriteFolderTupleScheme extends TupleScheme<FavoriteFolder> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FavoriteFolder struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFolderId()) {
        optionals.set(0);
      }
      if (struct.isSetFolderName()) {
        optionals.set(1);
      }
      if (struct.isSetParentFolderId()) {
        optionals.set(2);
      }
      if (struct.isSetPersonalUserId()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetFolderId()) {
        oprot.writeI64(struct.folderId);
      }
      if (struct.isSetFolderName()) {
        oprot.writeString(struct.folderName);
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeI64(struct.parentFolderId);
      }
      if (struct.isSetPersonalUserId()) {
        oprot.writeI64(struct.personalUserId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FavoriteFolder struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.folderId = iprot.readI64();
        struct.setFolderIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.folderName = iprot.readString();
        struct.setFolderNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.parentFolderId = iprot.readI64();
        struct.setParentFolderIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.personalUserId = iprot.readI64();
        struct.setPersonalUserIdIsSet(true);
      }
    }
  }

}

