/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PersonalUserErrorCode implements org.apache.thrift.TEnum {
  USER_EXISTS(1000),
  USER_NOT_FOUND(1001),
  PERSONAL_USER_RELATION_EXISTS(1002),
  COMPANY_USER_RELATION_EXISTS(1003),
  RELATION_NOT_FOUND(1004),
  FAVORITE_FOLDER_NOT_FOUND(1005),
  FAVORITE_CHART_NOT_FOUND(1006),
  FAVORITE_CHART_EXISTS(1007);

  private final int value;

  private PersonalUserErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PersonalUserErrorCode findByValue(int value) { 
    switch (value) {
      case 1000:
        return USER_EXISTS;
      case 1001:
        return USER_NOT_FOUND;
      case 1002:
        return PERSONAL_USER_RELATION_EXISTS;
      case 1003:
        return COMPANY_USER_RELATION_EXISTS;
      case 1004:
        return RELATION_NOT_FOUND;
      case 1005:
        return FAVORITE_FOLDER_NOT_FOUND;
      case 1006:
        return FAVORITE_CHART_NOT_FOUND;
      case 1007:
        return FAVORITE_CHART_EXISTS;
      default:
        return null;
    }
  }
}
