/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.personal.user.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ReqFavoriteChartOption implements org.apache.thrift.TBase<ReqFavoriteChartOption, ReqFavoriteChartOption._Fields>, java.io.Serializable, Cloneable, Comparable<ReqFavoriteChartOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReqFavoriteChartOption");

  private static final org.apache.thrift.protocol.TField FAVORITE_CHART_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("favoriteChartIds", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField PERSON_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("personUserId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField PARENT_FOLDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("parentFolderId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField XIAOHA_CHART_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("xiaohaChartId", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReqFavoriteChartOptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReqFavoriteChartOptionTupleSchemeFactory());
  }

  public Set<Long> favoriteChartIds; // optional
  public long personUserId; // optional
  public long parentFolderId; // optional
  public long xiaohaChartId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FAVORITE_CHART_IDS((short)1, "favoriteChartIds"),
    PERSON_USER_ID((short)2, "personUserId"),
    PARENT_FOLDER_ID((short)3, "parentFolderId"),
    XIAOHA_CHART_ID((short)4, "xiaohaChartId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FAVORITE_CHART_IDS
          return FAVORITE_CHART_IDS;
        case 2: // PERSON_USER_ID
          return PERSON_USER_ID;
        case 3: // PARENT_FOLDER_ID
          return PARENT_FOLDER_ID;
        case 4: // XIAOHA_CHART_ID
          return XIAOHA_CHART_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERSONUSERID_ISSET_ID = 0;
  private static final int __PARENTFOLDERID_ISSET_ID = 1;
  private static final int __XIAOHACHARTID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.FAVORITE_CHART_IDS,_Fields.PERSON_USER_ID,_Fields.PARENT_FOLDER_ID,_Fields.XIAOHA_CHART_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FAVORITE_CHART_IDS, new org.apache.thrift.meta_data.FieldMetaData("favoriteChartIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.PERSON_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("personUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PARENT_FOLDER_ID, new org.apache.thrift.meta_data.FieldMetaData("parentFolderId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.XIAOHA_CHART_ID, new org.apache.thrift.meta_data.FieldMetaData("xiaohaChartId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReqFavoriteChartOption.class, metaDataMap);
  }

  public ReqFavoriteChartOption() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReqFavoriteChartOption(ReqFavoriteChartOption other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFavoriteChartIds()) {
      Set<Long> __this__favoriteChartIds = new HashSet<Long>(other.favoriteChartIds);
      this.favoriteChartIds = __this__favoriteChartIds;
    }
    this.personUserId = other.personUserId;
    this.parentFolderId = other.parentFolderId;
    this.xiaohaChartId = other.xiaohaChartId;
  }

  public ReqFavoriteChartOption deepCopy() {
    return new ReqFavoriteChartOption(this);
  }

  @Override
  public void clear() {
    this.favoriteChartIds = null;
    setPersonUserIdIsSet(false);
    this.personUserId = 0;
    setParentFolderIdIsSet(false);
    this.parentFolderId = 0;
    setXiaohaChartIdIsSet(false);
    this.xiaohaChartId = 0;
  }

  public int getFavoriteChartIdsSize() {
    return (this.favoriteChartIds == null) ? 0 : this.favoriteChartIds.size();
  }

  public java.util.Iterator<Long> getFavoriteChartIdsIterator() {
    return (this.favoriteChartIds == null) ? null : this.favoriteChartIds.iterator();
  }

  public void addToFavoriteChartIds(long elem) {
    if (this.favoriteChartIds == null) {
      this.favoriteChartIds = new HashSet<Long>();
    }
    this.favoriteChartIds.add(elem);
  }

  public Set<Long> getFavoriteChartIds() {
    return this.favoriteChartIds;
  }

  public ReqFavoriteChartOption setFavoriteChartIds(Set<Long> favoriteChartIds) {
    this.favoriteChartIds = favoriteChartIds;
    return this;
  }

  public void unsetFavoriteChartIds() {
    this.favoriteChartIds = null;
  }

  /** Returns true if field favoriteChartIds is set (has been assigned a value) and false otherwise */
  public boolean isSetFavoriteChartIds() {
    return this.favoriteChartIds != null;
  }

  public void setFavoriteChartIdsIsSet(boolean value) {
    if (!value) {
      this.favoriteChartIds = null;
    }
  }

  public long getPersonUserId() {
    return this.personUserId;
  }

  public ReqFavoriteChartOption setPersonUserId(long personUserId) {
    this.personUserId = personUserId;
    setPersonUserIdIsSet(true);
    return this;
  }

  public void unsetPersonUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSONUSERID_ISSET_ID);
  }

  /** Returns true if field personUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetPersonUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSONUSERID_ISSET_ID);
  }

  public void setPersonUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSONUSERID_ISSET_ID, value);
  }

  public long getParentFolderId() {
    return this.parentFolderId;
  }

  public ReqFavoriteChartOption setParentFolderId(long parentFolderId) {
    this.parentFolderId = parentFolderId;
    setParentFolderIdIsSet(true);
    return this;
  }

  public void unsetParentFolderId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  /** Returns true if field parentFolderId is set (has been assigned a value) and false otherwise */
  public boolean isSetParentFolderId() {
    return EncodingUtils.testBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID);
  }

  public void setParentFolderIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PARENTFOLDERID_ISSET_ID, value);
  }

  public long getXiaohaChartId() {
    return this.xiaohaChartId;
  }

  public ReqFavoriteChartOption setXiaohaChartId(long xiaohaChartId) {
    this.xiaohaChartId = xiaohaChartId;
    setXiaohaChartIdIsSet(true);
    return this;
  }

  public void unsetXiaohaChartId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID);
  }

  /** Returns true if field xiaohaChartId is set (has been assigned a value) and false otherwise */
  public boolean isSetXiaohaChartId() {
    return EncodingUtils.testBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID);
  }

  public void setXiaohaChartIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __XIAOHACHARTID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FAVORITE_CHART_IDS:
      if (value == null) {
        unsetFavoriteChartIds();
      } else {
        setFavoriteChartIds((Set<Long>)value);
      }
      break;

    case PERSON_USER_ID:
      if (value == null) {
        unsetPersonUserId();
      } else {
        setPersonUserId((Long)value);
      }
      break;

    case PARENT_FOLDER_ID:
      if (value == null) {
        unsetParentFolderId();
      } else {
        setParentFolderId((Long)value);
      }
      break;

    case XIAOHA_CHART_ID:
      if (value == null) {
        unsetXiaohaChartId();
      } else {
        setXiaohaChartId((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FAVORITE_CHART_IDS:
      return getFavoriteChartIds();

    case PERSON_USER_ID:
      return Long.valueOf(getPersonUserId());

    case PARENT_FOLDER_ID:
      return Long.valueOf(getParentFolderId());

    case XIAOHA_CHART_ID:
      return Long.valueOf(getXiaohaChartId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FAVORITE_CHART_IDS:
      return isSetFavoriteChartIds();
    case PERSON_USER_ID:
      return isSetPersonUserId();
    case PARENT_FOLDER_ID:
      return isSetParentFolderId();
    case XIAOHA_CHART_ID:
      return isSetXiaohaChartId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReqFavoriteChartOption)
      return this.equals((ReqFavoriteChartOption)that);
    return false;
  }

  public boolean equals(ReqFavoriteChartOption that) {
    if (that == null)
      return false;

    boolean this_present_favoriteChartIds = true && this.isSetFavoriteChartIds();
    boolean that_present_favoriteChartIds = true && that.isSetFavoriteChartIds();
    if (this_present_favoriteChartIds || that_present_favoriteChartIds) {
      if (!(this_present_favoriteChartIds && that_present_favoriteChartIds))
        return false;
      if (!this.favoriteChartIds.equals(that.favoriteChartIds))
        return false;
    }

    boolean this_present_personUserId = true && this.isSetPersonUserId();
    boolean that_present_personUserId = true && that.isSetPersonUserId();
    if (this_present_personUserId || that_present_personUserId) {
      if (!(this_present_personUserId && that_present_personUserId))
        return false;
      if (this.personUserId != that.personUserId)
        return false;
    }

    boolean this_present_parentFolderId = true && this.isSetParentFolderId();
    boolean that_present_parentFolderId = true && that.isSetParentFolderId();
    if (this_present_parentFolderId || that_present_parentFolderId) {
      if (!(this_present_parentFolderId && that_present_parentFolderId))
        return false;
      if (this.parentFolderId != that.parentFolderId)
        return false;
    }

    boolean this_present_xiaohaChartId = true && this.isSetXiaohaChartId();
    boolean that_present_xiaohaChartId = true && that.isSetXiaohaChartId();
    if (this_present_xiaohaChartId || that_present_xiaohaChartId) {
      if (!(this_present_xiaohaChartId && that_present_xiaohaChartId))
        return false;
      if (this.xiaohaChartId != that.xiaohaChartId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ReqFavoriteChartOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFavoriteChartIds()).compareTo(other.isSetFavoriteChartIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFavoriteChartIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.favoriteChartIds, other.favoriteChartIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPersonUserId()).compareTo(other.isSetPersonUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersonUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.personUserId, other.personUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParentFolderId()).compareTo(other.isSetParentFolderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParentFolderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parentFolderId, other.parentFolderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetXiaohaChartId()).compareTo(other.isSetXiaohaChartId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXiaohaChartId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xiaohaChartId, other.xiaohaChartId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReqFavoriteChartOption(");
    boolean first = true;

    if (isSetFavoriteChartIds()) {
      sb.append("favoriteChartIds:");
      if (this.favoriteChartIds == null) {
        sb.append("null");
      } else {
        sb.append(this.favoriteChartIds);
      }
      first = false;
    }
    if (isSetPersonUserId()) {
      if (!first) sb.append(", ");
      sb.append("personUserId:");
      sb.append(this.personUserId);
      first = false;
    }
    if (isSetParentFolderId()) {
      if (!first) sb.append(", ");
      sb.append("parentFolderId:");
      sb.append(this.parentFolderId);
      first = false;
    }
    if (isSetXiaohaChartId()) {
      if (!first) sb.append(", ");
      sb.append("xiaohaChartId:");
      sb.append(this.xiaohaChartId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReqFavoriteChartOptionStandardSchemeFactory implements SchemeFactory {
    public ReqFavoriteChartOptionStandardScheme getScheme() {
      return new ReqFavoriteChartOptionStandardScheme();
    }
  }

  private static class ReqFavoriteChartOptionStandardScheme extends StandardScheme<ReqFavoriteChartOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReqFavoriteChartOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FAVORITE_CHART_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set40 = iprot.readSetBegin();
                struct.favoriteChartIds = new HashSet<Long>(2*_set40.size);
                for (int _i41 = 0; _i41 < _set40.size; ++_i41)
                {
                  long _elem42;
                  _elem42 = iprot.readI64();
                  struct.favoriteChartIds.add(_elem42);
                }
                iprot.readSetEnd();
              }
              struct.setFavoriteChartIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PERSON_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.personUserId = iprot.readI64();
              struct.setPersonUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PARENT_FOLDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.parentFolderId = iprot.readI64();
              struct.setParentFolderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // XIAOHA_CHART_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.xiaohaChartId = iprot.readI64();
              struct.setXiaohaChartIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReqFavoriteChartOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.favoriteChartIds != null) {
        if (struct.isSetFavoriteChartIds()) {
          oprot.writeFieldBegin(FAVORITE_CHART_IDS_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, struct.favoriteChartIds.size()));
            for (long _iter43 : struct.favoriteChartIds)
            {
              oprot.writeI64(_iter43);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetPersonUserId()) {
        oprot.writeFieldBegin(PERSON_USER_ID_FIELD_DESC);
        oprot.writeI64(struct.personUserId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeFieldBegin(PARENT_FOLDER_ID_FIELD_DESC);
        oprot.writeI64(struct.parentFolderId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetXiaohaChartId()) {
        oprot.writeFieldBegin(XIAOHA_CHART_ID_FIELD_DESC);
        oprot.writeI64(struct.xiaohaChartId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReqFavoriteChartOptionTupleSchemeFactory implements SchemeFactory {
    public ReqFavoriteChartOptionTupleScheme getScheme() {
      return new ReqFavoriteChartOptionTupleScheme();
    }
  }

  private static class ReqFavoriteChartOptionTupleScheme extends TupleScheme<ReqFavoriteChartOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReqFavoriteChartOption struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFavoriteChartIds()) {
        optionals.set(0);
      }
      if (struct.isSetPersonUserId()) {
        optionals.set(1);
      }
      if (struct.isSetParentFolderId()) {
        optionals.set(2);
      }
      if (struct.isSetXiaohaChartId()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetFavoriteChartIds()) {
        {
          oprot.writeI32(struct.favoriteChartIds.size());
          for (long _iter44 : struct.favoriteChartIds)
          {
            oprot.writeI64(_iter44);
          }
        }
      }
      if (struct.isSetPersonUserId()) {
        oprot.writeI64(struct.personUserId);
      }
      if (struct.isSetParentFolderId()) {
        oprot.writeI64(struct.parentFolderId);
      }
      if (struct.isSetXiaohaChartId()) {
        oprot.writeI64(struct.xiaohaChartId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReqFavoriteChartOption struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set45 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.favoriteChartIds = new HashSet<Long>(2*_set45.size);
          for (int _i46 = 0; _i46 < _set45.size; ++_i46)
          {
            long _elem47;
            _elem47 = iprot.readI64();
            struct.favoriteChartIds.add(_elem47);
          }
        }
        struct.setFavoriteChartIdsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.personUserId = iprot.readI64();
        struct.setPersonUserIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.parentFolderId = iprot.readI64();
        struct.setParentFolderIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.xiaohaChartId = iprot.readI64();
        struct.setXiaohaChartIdIsSet(true);
      }
    }
  }

}

